[workspace]
members = ["cmprust", "georust", "linrust", "ppmrust", "renrust"]

resolver = "2"

[workspace.dependencies]
georust = { path = "georust" }
linrust = { path = "linrust" }
ppmrust = { path = "ppmrust" }
renrust = { path = "renrust" }
