[workspace]
members = ["cmprust", "georust", "linrust", "ppmrust"]

resolver = "2"

[workspace.dependencies]
georust = { path = "georust" }
linrust = { path = "linrust" }
ppmrust = { path = "ppmrust" }
